---
title: "DESeq2 negative binomial regression using peak count data"
output:
  workflowr::wflow_html:
    toc: true
    toc_depth: 2
editor_options:
  chunk_output_type: console
---

```{r setup, dev=c('png'), include=F}
knitr::opts_chunk$set(dev = c('png'))
knitr::opts_chunk$set(autodep = TRUE)

```
 
```{r include=F}
.libPaths("/net/snowwhite/home/aujackso/R/x86_64-pc-linux-gnu-library/4.0");
library(dplyr) 
library(readr)
library(ggplot2)
library(DESeq2) 
library(RColorBrewer)
library(grid)
library(gridExtra)
library(knitr)
options(scipen=1, digits=5)
options(nwarnings=10000)
invnorm = function(x, seed) {
  set.seed(seed)
  qnorm((rank(x, na.last="keep", ties.method="random") - 0.5) / sum(!is.na(x)))
}

scatterp<-function(ds, trait, xstr, ystr) {		
Mycolors = c("#a6cee3", "#1f78b4", "#8dd3c7", "#b2df8a", "#33a02c",
           "#6a3d9a","#fb9a99", "#fdbf6f", "#cab2d6", "#b15928", "#e31a1c", 
           "#ffff33","#999999")
	return(
	ggplot(ds, aes(x=sgnp_deseq, y=sgnp_calc, color=cell)) + 
		geom_point() + 
		theme(axis.title=element_text(size=10)) +
		geom_abline(slope=1, intercept=0, colour="gray") + 
		ggtitle(paste0(trait)) + 
		xlab(xstr) + 
		ylab(ystr) +
		#coord_cartesian(xlim=c(min(temp),max(temp)), ylim=c(min(temp),max(temp)) ) + 
		theme_bw() + 
		scale_colour_manual(values=Mycolors)  + 
		theme(legend.position="none") + 
		#theme(axis.text.x=element_text(angle=0, size=12)) + 
		#theme(axis.text.y=element_text(size=12)) + 
		geom_hline(yintercept=0, colour="black", size=0.1) + 
		geom_vline(xintercept=0, colour="black", size=0.1) +  
		facet_wrap(~cell, scales="free") +
	theme(strip.text.x=element_text(size=8))

        )
}


celltype<-c("Adipocyte", "Endothelial", "Macrophage", "Mesenchymal_Stem_Cell",  "Neuromuscular_junction", "Neuronal", "Satellite_Cell", "Smooth_Muscle", "T_cell", "Type_1", "Type_2a", "Type_2x")
traits<-c("SEX", "AGE", "T2D", "INS", "BMI",  "GLU", "HEIGHT", "WEIGHT", "WAIST", "WHR", "HIP", "S_ALAT", "S_hs_CRP", "fS_Kol", "fS_Kol_HDL", "fS_Kol_LDL_c", "fS_Trigly", "GL30", "GL60", "GL120", "S_LipoA1", "S_LipoB", "fS_C_pept", "fS_Krea", "S_GT", "S_Uraat", "fS_C_pept_30", "S_Insu_30", "B_GHb_A1C", "glu_2h_biopsy", "daily_energy_expenditure", "total_daily_physical_activity", "moderate_physical_activity", "strenuous_physical_activity",  "p_insu", "p_insu_30", "p_insu_60", "p_insu_120", "RFM", "sbp", "dbp", "ApoB_A1_ratio", "Ins_AUC_0to30", "Glu_AUC_0to30", "InsSec30", "InsGenIn", "DIo", "CpepGenIn", "HOMA", "matsuda_4pt", "matsuda_3pt", "LTPA_duration_all", "LTPA_duration_cond", "LTPA_duration_noncond", "LTPA_energy_all", "LTPA_energy_cond", "LTPA_energy_noncond", "LTPA_energy_light", "LTPA_energy_moderate", "LTPA_energy_modvig", "LTPA_energy_vigorous", "sleep_biopsy", "totalcw", "sleep_24h", "GL0")      
traits2<-c("SEX.M", "AGE", "T2D", "INSFAST", "BMI", "GLUFAST", "HEIGHT", "WEIGHT", "WAIST", "WHR", "HIP", "ALAT", "CRP", "CHOL", "HDL", "LDL", "TG", "GL30", "GL60", "GL120", "APOA1", "APOB", "CPEP", "CREAT", "GT", "URIC", "CPEP30", "S_INS30", "HBA1C", "GLU2H", "ENERGY", "PA_TOT", "PA_MOD", "PA_STREN", "INS0", "INS30", "INS60", "INS120", "RFM", "SBP", "DBP", "APOB.A1.RATIO", "INS_AUC_0_30", "GLU_AUC_0_30", "INSSEC30", "INSGENIN", "DI", "CPEPGENIN", "HOMA", "MATSUDA4", "MATSUDA3", "LTPA.DUR.ALL", "LTPA.DUR.COND", "LTPA.DUR.NONCOND", "LTPA.EN.ALL", "LTPA.EN.COND", "LTPA.EN.NONCOND", "LTPA.EN.LIGHT", "LTPA.EN.MOD", "LTPA.EN.MODVIG", "LTPA.EN.VIG", "SLEEP", "ALCOHOL", "SLEEP24H", "GL0")

trtfactor=c("HEIGHT", "BMI", "HIP", "RFM", "WAIST", "WEIGHT", "WHR", "CHOL", "HDL", "LDL", "TG", "APOA1", "APOB", "APOB.A1.RATIO", "GLUFAST", "GL0", "GL30", "GL60", "GL120", "GLU_AUC_0_30", "GLU2H",  "HBA1C", "T2D", "INSFAST", "INS0", "S_INS30", "INS30",
 "INS60", "INS120", "CPEP", "CPEP30", "INS_AUC_0_30", "INSSEC30", "INSGENIN", "DI", "CPEPGENIN", "HOMA", "MATSUDA4", "MATSUDA3", "CRP", "CREAT", "GT", "ALAT", "URIC", "SBP", "DBP", "ENERGY",  "PA_TOT", "PA_MOD", "PA_STREN", "LTPA.DUR.ALL", "LTPA.DUR.COND", "LTPA.DUR.NONCOND", "LTPA.EN.ALL", "LTPA.EN.COND",
  "LTPA.EN.NONCOND", "LTPA.EN.LIGHT", "LTPA.EN.MOD", "LTPA.EN.MODVIG", "LTPA.EN.VIG",  "SLEEP", "SLEEP24H", "ALCOHOL", "SEX.M", "AGE")

barplot_fdr<-function(ds, yvar, ystr, titlestr){	
myColors <- c("#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2",
 "#D55E00", "#CC79A7", "#999999")
 	ds$trait2<-factor(ds$trait2, levels=trtfactor)
	return(ggplot(data=ds, aes(x=trait2, y=yvar, fill=model)) + 
	geom_bar(stat='identity', position=position_dodge(),width=1) + 
	theme(strip.text.x=element_text(size=8)) + 
	labs(x="TRAIT", y=ystr) + 
	ggtitle(label=paste0(titlestr))  + 
	theme(axis.text.x=element_text(size=10),legend.position="bottom") + 
	scale_fill_manual(values=myColors) + 
	theme(axis.text.x=element_text(angle=90, hjust=1, vjust=0.5))
 )
}


```

Make 'FINAL' phenotype and peak datasets for use with DESEq2
Drop samples with <=10 nuclei
Drop peaks with >75% missingness across remaining samples
```{r prep_data_atac, cache=FALSE, echo=FALSE, warning=FALSE, message=FALSE, include=TRUE, eval=FALSE}
atac.nuc<-readRDS("data/df.atac.nuc.Rds") 
who.use.atac<-atac.nuc$labelcode

#set of people to be used in analysis, Rds made using 0_make_ds.Rmd
phen<-read_csv("data/tissue.csv")  %>% dplyr::rename(GLU=glu_fast_biopsy, AGE=age_biopsy, INS=S_Insu, BMI=bmi, WHR=whr) %>% filter(labelcode %in% all_of(who.use.atac)) 
batchnuc<-read_tsv("output/atac_covars.txt", guess_max=3649) %>% select(labelcode, batch, tot_nuc_allcelltypes) %>% unique()
phen0<-merge(phen, batchnuc, by="labelcode") #281


# non-trait specific exclusions
pds.orig<-list()
eds.orig<-list()
samps<-data.frame()
peakused<-data.frame()
for (i in 1:length(celltype)) {
	
	print(paste0("reading phenotypes for ",celltype[i]))
	phen.orig<-phen0 %>%
		mutate(T2D=as.factor(ifelse(ogtt_status_paper=="T2D",1,ifelse(ogtt_status_paper=="NGT",0,NA))))	
	# Merge in tss_enrichment, n_nuclei (does not include MFM)
	tss.orig<-read_tsv("output/atac_covars.txt", guess_max=3649) 
	tss<-tss.orig  %>% dplyr::filter(coarse_cluster_name==celltype[i]) %>% select(labelcode, fraction_mitochondrial_median, n_nuclei, tss_enrichment, total_reads)
   # filter on 10 nuclei per sample - new  Nov 10 2022 
   	
	phen.orig<-merge(phen.orig, tss, by="labelcode", all.x=TRUE)  %>% filter(n_nuclei>10)
	
	print(paste0(celltype[i], " samples read in: ", nrow(phen.orig)))

	pds.orig[[i]]=phen.orig 
	keep<-phen.orig$labelcode

	#keep track of samples for each celltype
	temp<-phen.orig %>% mutate(celltype=celltype[i]) %>% select(celltype, labelcode)
	if(i==1){samps<-temp}
	if(i>1) {samps <- rbind.data.frame(samps,temp)}
	

	print(paste0("reading counts for ",celltype[i]))
	eds<-read_tsv(paste0("output/atac.counts.no0.",celltype[i],".txt")) %>%
		select(peak, all_of(keep))

	#  Drop peaks missing data on more than 75% of samples - keep peaks with non0 counts for at least 25% of samples  
	print(paste0("N peaks initial for ",celltype[i],": ",nrow(eds)))
	peak<-eds$peak
	count.tmp<-eds %>% dplyr::select(-peak)
	nsamp<-ncol(count.tmp)
	count.tmp<-as_tibble(count.tmp) 
	ct.non0=rowSums(count.tmp!=0)
	prop.non0=ct.non0/nsamp
	keep.peak <- cbind.data.frame(peak, prop.non0) %>% dplyr::filter(prop.non0>=0.25) %>% pull(peak)
	eds.orig[[i]]<-eds %>% dplyr::slice(match(keep.peak, peak))
	print(paste0("N peaks after excluding >=75% missing ",celltype[i],": ",nrow(eds.orig[[i]])))
	n.peak.keep<-length(keep.peak)
	cell<-celltype[i]
	temp<-cbind.data.frame(cell, n.peak.keep)
	if(i==1){peakused<-temp}
	if(i>1) {peakused <- rbind.data.frame(peakused,temp)}

saveRDS(eds.orig[[i]],paste0("data/ATAC.eds.orig.",celltype[i],".Rds"))
saveRDS(pds.orig[[i]],paste0("data/ATAC.pds.orig.",celltype[i],".Rds"))
	
}
write.table(samps, "data/ATAC.samples_used_per_celltype.txt", col.names=T, row.names=F, sep="\t", quote=F)
write.table(peakused, "data/Npeaks_used_per_celltype.txt", col.names=T, row.names=F, sep="\t", quote=F)

```


Write out the mean counts per ATAC peak per cell type

```{r atac_mean_counts, cache=FALSE, echo=FALSE, warning=FALSE, message=FALSE, include=TRUE, eval=FALSE}
celltype<-c("Adipocyte", "Endothelial", "Macrophage", "Mesenchymal_Stem_Cell", "Neuromuscular_junction", "Neuronal", "Satellite_Cell", "Smooth_Muscle", "T_cell", "Type_1", "Type_2a", "Type_2x")
for (i in 1:length(celltype)) {
pds.orig<-readRDS(paste0("data/ATAC.pds.orig.",celltype[i],".Rds"))
eds.orig<-readRDS(paste0("data/ATAC.eds.orig.",celltype[i],".Rds"))
	print(celltype[i])
	pds <- pds.orig %>% dplyr::filter(n_nuclei>10)
	samps<-pds %>% pull(labelcode) #to select peak columns
	eds<-eds.orig %>% dplyr::select(peak, all_of(samps))	
	peak<-eds$peak
	eds<-eds %>% dplyr::select(-peak)
	mean.pk.ct<-rowMeans(eds)
	out<-cbind.data.frame(peak, mean.pk.ct)
	write.table(out, paste0("data/atac_meanpkct_",celltype[i],".txt"), col.names=T, row.names=F, 	quote=F, sep="\t")
}	
```


